# Generated by Django 5.0.3 on 2024-03-13 07:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budget', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='budget',
            name='price_end',
        ),
        migrations.RemoveField(
            model_name='budget',
            name='price_start',
        ),
        migrations.AddField(
            model_name='budget',
            name='budget_title',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='budget',
            name='description',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='budget',
            name='expenses',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='budget',
            name='amount',
            field=models.DecimalField(decimal_places=2, max_digits=15, null=True),
        ),
        migrations.AlterField(
            model_name='budget',
            name='user_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
