# Generated by Django 5.0.3 on 2024-03-13 08:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budget', '0002_remove_budget_price_end_remove_budget_price_start_and_more'),
        ('finance', '0002_remove_transaction_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='budget',
            name='category',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.RemoveField(
            model_name='budget',
            name='user_id',
        ),
        migrations.DeleteModel(
            name='Category',
        ),
    ]
