# Generated by Django 5.0.3 on 2024-03-18 05:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budget', '0004_category_budget_user_id'),
        ('finance', '0004_rename_from_account_id_transfer_from_account_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='budget',
            name='user_id',
        ),
        migrations.AddField(
            model_name='budget',
            name='account',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='finance.account'),
        ),
    ]
