# Generated by Django 5.0.3 on 2024-03-15 07:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0003_alter_account_user_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='transfer',
            old_name='from_account_id',
            new_name='from_account',
        ),
        migrations.RenameField(
            model_name='transfer',
            old_name='to_account_id',
            new_name='to_account',
        ),
    ]
