# Generated by Django 5.0.3 on 2024-03-12 08:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Investment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('investment_type', models.CharField(max_length=50)),
                ('value', models.DecimalField(decimal_places=2, max_digits=15)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=15)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='InvestmentTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=15)),
                ('transaction_type', models.CharField(max_length=50)),
                ('description', models.TextField()),
                ('transaction_date', models.DateTimeField(auto_now_add=True)),
                ('investment_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='investment.investment')),
            ],
        ),
    ]
